### ISSUE TITLE
merging MAPSPAM and 'Monfreda' datasets

### ISSUE THREAD

**Issue by AaronPlex** [GarrettLab/CroplandConnectivity#93]
check that if users specify the same crop in both datasets, generate a map of the mean between MAPSPAM and Monfreda.

sum if crop are different in each dataset

**Comment by krishnakeshav** [comment]
The behavior is as expected. If the crop is specified in both monfreda and mapspam, the mean density map is generated. In case of multiple hosts, they are all added if the extents are matching to producde host density.
